# Generated by Django 6.0 on 2025-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'created_at'], name='shared_outb_status_fe1d9d_idx'),
        ),
        migrations.AlterModelTable(
            name='outboxevent',
            table='shared_outbox_event',
        ),
    ]
