# Generated by Django 6.0 on 2026-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_remove_outboxevent_version_outboxevent_event_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['aggregate_id'], name='shared_outb_aggrega_f52992_idx'),
        ),
    ]
