# Generated by Django 6.0 on 2026-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_outboxevent_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='processing_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
