# FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.1

# ENV discovery.type=single-node
# ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

# EXPOSE 9200 9300

FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.1
